apiVersion: batch/v1
kind: Job
metadata:
  name: n8n-stress-job
  namespace: n8n-workshop
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:8.10.1
          env:
            - name: WEBHOOK_PATH
              value: "workshop/demo"
          command:
            - sh
            - -c
            - |
              for i in $(seq 1 100000); do
                curl -s http://n8n:5678/webhook/${WEBHOOK_PATH} >/dev/null
                sleep 0.05
              done
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 150m
              memory: 96Mi
