---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: dragonfly-operator
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Operator configuration
    replicaCount: 1
