---
# Dragonfly Operator from official GitHub manifest
# Source: https://github.com/dragonflydb/dragonfly-operator
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/dragonflydb/dragonfly-operator
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: dragonfly-operator
  path: ./manifests
  prune: true
  wait: true
